### ISSUE TITLE
Wiki entries can obscure other entries using <!--

### ISSUE THREAD

**Issue by ljcooke** [XXIIVV/Webring#271]
**Please describe the issue in the wiki:**

The wiki does not escape `<!--`, which allows one entry in a category to hide any entries that follow.

Most HTML tags other than `<script>` don't seem to be escaped either, but this can be fun…

```
UNCATEGORIZED
  Hack the planet
    <marquee style="font: 2.0em 'Comic Sans MS'">fee</marquee>
    <marquee style="font: 2.5em 'Comic Sans MS'">fi</marquee>
    <marquee style="font: 3.0em 'Comic Sans MS'">fo</marquee>
    <marquee style="font: 3.5em 'Comic Sans MS'">fum</marquee>
    <!--
```

<img width="525" alt="Screen Shot 2019-08-12 at 20 18 15" src="https://user-images.githubusercontent.com/14365947/62858705-57ca2b80-bd3e-11e9-8158-350afc54d6bc.png">

**Comment by neauoire** [comment]
We trust our members to police each other against this kind of stuff, but you're right, as the wiki grows, we could add more failsafes like this. 👍

**Comment by ckipp01** [comment]
I think another good reason to add in some sort of **cleaning** is also so that we keep our data structures clean and separate from the templating.

 For example, I noticed that @AAorris added in some titles to his entries, which is cool, but it introduces and mixes templating with the data structure, which I don't like. Another negative to this is that anyone else building companion apps to the webring can't trust that the data sources are pure data anymore. (This is more of a selfish one, since now the webring-cli wiki viewer shows that html, and the entries are a mix of text and raw html). The Compendium app that @jrc03c made will have the same issue.

My opinion would be that we strip html out which encourages people to not put it in, leaving the data structures... data structures.

**Comment by neauoire** [comment]
I agree, there should be no html in there at all.

**Comment by ljcooke** [comment]
Good point about mixing templating with data.

It might be enough to replace the characters `< > &` with `&lt; &gt; &amp;`.
