### ISSUE TITLE
[webring] should thumbnails be present?

### ISSUE THREAD

**Issue by dym-sh** [XXIIVV/Webring#301]
where is nearly a hundred of sites to browse, and thumbnails might help to distinguish them from one another a bit faster.

should prbly be auto generated on add and monthly(?) after.

**Comment by ckipp01** [comment]
Imo, thumbnails may not be the best answer.

I guess my question would be what is the goal of being able to distinguish them? Is it to find a certain type of site? If so, I think when we implement filtering on site type, it will take care of that. Or, is it to find a site that you enjoyed in the past?

**Comment by dym-sh** [comment]
i visited webring on my phone and saw a ~100 links. i honestly lost my will to do anything and went to sleep.

**Comment by ckipp01** [comment]
Um, ok. Well, I'm not 100% sure how to respond to that, but I guess my original question still remains. To expand on it a bit, I think it is a good thing to think about what the main point of the "portal" page is for. I think traditionally the webring page that lists all the sites is just that, a page that lists all the sites and not much more because most of the time as one is navigating around the webring, they aren't actually going to the list page but rather to the next site on the ring.

That to say, it doesn't mean that we should only treat it that way. I think it's neat to have a page that lists all of the sites, shows maybe what type of site it is, etc. That is where the filtering comes in (#213), and will hopefully help with that a bit. This again leads to the original question, did you think of the thumbnails as a way to find a previous site you had visited? To get a quick preview of a site? Or was it just a random thought? I think the answer to that question may help us discuss the possibility and whether it's a good idea or not.

**Comment by neauoire** [comment]
I don't think loading 100 thumbnails is going to help anything. 
I would prefer we stick to tags and implement filtering.

**Comment by ckipp01** [comment]
Going to close this in favor of just implementing filters.

#213
