### ISSUE TITLE
should sites.js just be json?

### ISSUE THREAD

**Issue by dym-sh** [XXIIVV/Webring#306]
it would make more sense, given the array of sites is the only thing it returns

**Comment by ckipp01** [comment]
As someone who has multiple tools hooked into the webring, I get what you're saying since they break every time this changes structure, or someone puts an entry in which is valid in JS, but not following the right pattern. It's also just data, so it's appropriate. However...

I think this was possibly discussed before somewhere on here, but I know it's an important value of @neauoire to keep this working locally with no build process, and also acting the same that it does live when running locally. Mainly meaning that switching this file to be JSON would sort of not work since there would either need to be some sort of build step to incorporate it, or we'd need to fetch it. There may be other ways to do this, but I'm not aware of how to do it, and I've tried. So, if there is a way to make this JSON without a build process or without having to fetch it, let's do it. However, if there isn't, then we are stuck with it just being an array.

**Comment by dym-sh** [comment]
just load json in a \<script\> tag 🤷‍♂️

https://stackoverflow.com/a/7956249

**Comment by dym-sh** [comment]
ok, upon further investigation, `<script src='sites.json' type='application/json'></script>` did not work.
also, local `fetch` of a json file trows an error -- needs CORS on http(s) and refuses to handle `file:///` for security concerns.

**Comment by ckipp01** [comment]
So I also did a bit of digging in this over the past couple days. There just isn't a good way to do this without hosting the file somewhere as you said. At that point, again, we are sort of getting away from the just cloning and running the ring. I'm going to assume @neauoire doesn't want to something to serve this separately, and I wouldn't even be in favor of doing that.

For now, I think we should just leave as is. I'll just update my parsers to accommodate the new format. I'll wait for @neauoire to confirm before closing the issue.

**Comment by dym-sh** [comment]
dont really see the point of keeping raw `file:///` functionality here, since any action after loading the page will require internet connection, be that browsing portal or _opening_ wiki or hallway :)

adding each .ndtl and twtxt file from sites list to appcache.manifest would be a probable solution, but that will be fairly tedious w/o git-hooks/github-actions/other kind of build process.

**Comment by neauoire** [comment]
I've looked into this as well, we ought to keep this simple and stupid.
The webring will ever have a build step.

**Comment by dym-sh** [comment]
that's my point, there is no way to make/keep it "offline first" w/o crawling every peer while online.
so, by converting sites.js to json we are not really lose any offline capability, since there isn't any atm.

**Comment by neauoire** [comment]
Will it require to spin localhost?

**Comment by dym-sh** [comment]
well, yes, but that can be done with a doube-clickable script file
